---
id: rubykansai75-ruby24
base_name: ruby_2_4
tags:
- ruby
presentation_date: '2016-11-05'
version: 2016.11.05
licenses: []
slideshare_id: rubykansai75-ruby24
speaker_deck_id: ruby-2-dot-4-0-falsezhu-nafei-hu-huan
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :markdown
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
